# Generated by Django 4.1 on 2022-09-11 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(max_length=50, verbose_name='学習範囲')),
                ('homework', models.CharField(max_length=50, verbose_name='宿題')),
                ('date', models.DateTimeField(null=True, verbose_name='日付')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('remark', models.CharField(max_length=100, verbose_name='備考')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
