# Generated by Django 4.1 on 2022-09-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
            preserve_default=False,
        ),
    ]
