# Generated by Django 4.1 on 2022-09-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth',
            field=models.DateTimeField(null=True, verbose_name='生年月日'),
        ),
    ]
