# Generated by Django 4.1.1 on 2022-09-11 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_juku_delete_juku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='塾名前')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='juku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.juku'),
        ),
    ]
