# Generated by Django 4.1.1 on 2022-09-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_juku_customuser_juku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='juku',
        ),
        migrations.DeleteModel(
            name='Juku',
        ),
    ]
