# Generated by Django 4.1 on 2022-09-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_juku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('teacher', '講師'), ('student', '生徒')], max_length=20, verbose_name='講師or生徒'),
        ),
    ]
