# Generated by Django 4.1.1 on 2022-09-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth',
            field=models.DateTimeField(null=True, verbose_name='生年月日'),
        ),
    ]
