# Generated by Django 4.1 on 2022-09-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_customuser_birth'),
        ('users', '0016_remove_customuser_following_follow'),
    ]

    operations = [
    ]
