# Generated by Django 4.1 on 2022-09-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_merge_20220913_1814"),
        ("users", "0017_merge_20220913_1824"),
    ]

    operations = []
