# Generated by Django 4.1.1 on 2022-09-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='塾名')),
                ('news', models.CharField(max_length=200, null=True, verbose_name='お知らせ')),
            ],
        ),
        migrations.DeleteModel(
            name='Zuku',
        ),
    ]
