# Generated by Django 4.1 on 2022-09-11 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(null=True, verbose_name='年月日')),
                ('type', models.CharField(choices=[('定期', '定期'), ('模試', '模試')], max_length=20, verbose_name='定期or模試')),
                ('subject', models.CharField(choices=[('国語', '国語'), ('数学', '数学'), ('理科', '理科'), ('社会', '社会'), ('英語', '英語')], max_length=20, verbose_name='科目選択')),
                ('score', models.FloatField(verbose_name='点数')),
                ('averagescore', models.FloatField(verbose_name='平均点')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
