# Generated by Django 4.1 on 2022-09-11 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="records",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="records",
            name="subject",
            field=models.CharField(
                choices=[
                    ("国語", "国語"),
                    ("数学", "数学"),
                    ("理科", "理科"),
                    ("社会", "社会"),
                    ("英語", "英語"),
                ],
                max_length=20,
                verbose_name="科目選択",
            ),
        ),
        migrations.AlterField(
            model_name="records",
            name="type",
            field=models.CharField(
                choices=[("定期", "定期"), ("模試", "模試")],
                max_length=20,
                verbose_name="定期or模試",
            ),
        ),
    ]
