# Generated by Django 4.1.1 on 2022-09-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='subject',
            field=models.CharField(choices=[('国語', '国語'), ('数学', '数学'), ('理科', '理科'), ('社会', '社会'), ('英語', '英語')], max_length=20, verbose_name='科目選択'),
        ),
        migrations.AlterField(
            model_name='records',
            name='type',
            field=models.CharField(choices=[('定期', '定期'), ('模試', '模試')], max_length=20, verbose_name='定期or模試'),
        ),
    ]
