# Generated by Django 4.1 on 2022-09-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='averagescore',
        ),
        migrations.RemoveField(
            model_name='record',
            name='score',
        ),
        migrations.RemoveField(
            model_name='record',
            name='subject',
        ),
        migrations.AddField(
            model_name='record',
            name='average_english',
            field=models.FloatField(default=50, verbose_name='英語の平均点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='average_japanese',
            field=models.FloatField(default=60, verbose_name='国語の平均点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='average_math',
            field=models.FloatField(default=30, verbose_name='数学の平均点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='average_sience',
            field=models.FloatField(default=40, verbose_name='理科の平均点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='average_social',
            field=models.FloatField(default=21, verbose_name='社会の平均点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='diviation_english',
            field=models.FloatField(default=33, verbose_name='英語の偏差値'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='diviation_japanese',
            field=models.FloatField(default=44, verbose_name='国語の偏差値'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='diviation_math',
            field=models.FloatField(default=55, verbose_name='数学の偏差値'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='diviation_sience',
            field=models.FloatField(default=66, verbose_name='理科の偏差値'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='diviation_social',
            field=models.FloatField(default=77, verbose_name='社会の偏差値'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='score_english',
            field=models.FloatField(default=88, verbose_name='英語の点数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='score_math',
            field=models.FloatField(default=99, verbose_name='数学の点数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='score_sience',
            field=models.FloatField(default=100, verbose_name='理科の点数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='score_social',
            field=models.FloatField(default=23, verbose_name='社会の点数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='socre_japanese',
            field=models.FloatField(default=34, verbose_name='国語の点数'),
            preserve_default=False,
        ),
    ]
