# Generated by Django 4.1 on 2022-09-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_record_averagescore_remove_record_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='day',
            new_name='date',
        ),
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(default='前期中間テスト', max_length=50, verbose_name='テスト名'),
            preserve_default=False,
        ),
    ]
