# Generated by Django 4.1 on 2022-09-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_records_subject_alter_records_type'),
        ('records', '0002_records_student_alter_records_subject_and_more'),
    ]

    operations = [
    ]
