# Generated by Django 4.1 on 2022-09-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_day_record_date_record_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='socre_japanese',
            new_name='score_japanese',
        ),
    ]
