# Generated by Django 4.1 on 2022-09-11 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_records_subject_alter_records_type'),
        ('records', '0003_record_delete_records'),
    ]

    operations = [
    ]
