# Generated by Django 4.1 on 2022-09-11 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_merge_20220911_1145'),
        ('records', '0004_merge_20220911_1159'),
    ]

    operations = [
    ]
