# Generated by Django 4.1 on 2022-09-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('yellow', 'yellow'), ('green', 'green'), ('green', 'green'), ('gray', 'gray'), ('black', 'black'), ('white', 'white')], default='res', max_length=20, verbose_name='色'),
            preserve_default=False,
        ),
    ]
