# Generated by Django 4.1 on 2022-09-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('danger', 'red'), ('primary', 'blue'), ('warning', 'yellow'), ('success', 'green'), ('secondary', 'gray'), ('dark', 'black'), ('light', 'white')], max_length=20, verbose_name='色'),
        ),
    ]
