# Generated by Django 4.1 on 2022-09-13 03:02

import diaries.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diaries', '0002_diary_subject_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0004_alter_subject_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日時')),
                ('diary', models.ForeignKey(null=True, on_delete=diaries.models.Diary, to='diaries.diary')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('users', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
